# Database Configuration
MYSQL_HOST=localhost
MYSQL_USER=your_mysql_username
MYSQL_PASSWORD=your_mysql_password
MYSQL_DB=qrshield_db

# API Keys for Security Services
VIRUSTOTAL_API_KEY=your_virustotal_api_key_here
GOOGLE_SAFE_BROWSING_API_KEY=your_google_safe_browsing_api_key_here
URLSCAN_API_KEY=your_urlscan_api_key_here

# Optional: Additional API Keys
WHOIS_API_KEY=your_whois_api_key_here
IP_GEOLOCATION_API_KEY=your_ip_geolocation_api_key_here

# Application Settings
DEBUG=True
APP_SECRET_KEY=your_secret_key_here_change_in_production
MAX_FILE_SIZE=10485760  # 10MB in bytes
ALLOWED_FILE_TYPES=image/jpeg,image/png,image/gif,image/bmp